name: "Post Commit Hook"

on:
  push:
    branches-ignore:
      - main

run-name: "[${{ github.sha }}] build"

jobs:
  run-build:
    uses: kgusarov-public-projects/cilib/.github/workflows/workflow-1.yml
