name: "Release"

on:
  push:
    branches:
      - main

run-name: "[${{ github.sha }}] release"

jobs:
  perform-release:
    name: "Perform Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "21"
          cache: "maven"
      - uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
              "id": "public-artifacts",
              "username": "${{ secrets.ADO_MAVEN_USERNAME }}",
              "password": "${{ secrets.ADO_MAVEN_PASSWORD }}"
            }]
      - uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "npm"
      - name: NPM Install
        run: npm ci
      - name: Perform Release
        run: npx semantic-release
